package com.drools_poc.drools_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test3 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Test3() {
    }




}