package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPLICANT_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "APPLICANT_ID_GENERATOR", sequenceName = "APPLICANT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Age")
	private int age;

	@org.kie.api.definition.type.Label(value = "Money")
	private int money;

	@org.kie.api.definition.type.Label(value = "Approved")
	private boolean approved;

	public Applicant() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getMoney() {
		return this.money;
	}

	public void setMoney(int money) {
		this.money = money;
	}

	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

	public Applicant(java.lang.Long id, java.lang.String name, int age,
			int money, boolean approved) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.money = money;
		this.approved = approved;
	}

}