package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Prepayment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PREPAYMENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PREPAYMENT_ID_GENERATOR", sequenceName = "PREPAYMENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Total interest")
	private java.lang.Integer totalInterest;

	@org.kie.api.definition.type.Label("Amount")
	private java.lang.Long amount;

	@org.kie.api.definition.type.Label("Date")
	private java.time.LocalDate date;

	@org.kie.api.definition.type.Label(value = "No Of Months")
	private java.lang.Integer noOfMonths;

	public Prepayment() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Integer getTotalInterest() {
		return this.totalInterest;
	}

	public void setTotalInterest(java.lang.Integer totalInterest) {
		this.totalInterest = totalInterest;
	}

	public java.lang.Long getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Long amount) {
		this.amount = amount;
	}

	public java.time.LocalDate getDate() {
		return this.date;
	}

	public void setDate(java.time.LocalDate date) {
		this.date = date;
	}

	public java.lang.Integer getNoOfMonths() {
		return this.noOfMonths;
	}

	public void setNoOfMonths(java.lang.Integer noOfMonths) {
		this.noOfMonths = noOfMonths;
	}

	public Prepayment(java.lang.Long id, java.lang.Integer totalInterest,
			java.lang.Long amount, java.time.LocalDate date,
			java.lang.Integer noOfMonths) {
		this.id = id;
		this.totalInterest = totalInterest;
		this.amount = amount;
		this.date = date;
		this.noOfMonths = noOfMonths;
	}

}