package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Prepayment implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "PREPAYMENT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "PREPAYMENT_ID_GENERATOR", sequenceName = "PREPAYMENT_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Total interest")
	private double totalInterest;

	@org.kie.api.definition.type.Label("Amount")
	private Double amount;

	@org.kie.api.definition.type.Label("Date")
	private java.time.LocalDate date;

	@org.kie.api.definition.type.Label("No Of Months")
	private java.lang.Integer noOfMonths;

	@org.kie.api.definition.type.Label("Days To Terminate")
	private java.lang.Integer daysToTerminate;

	@org.kie.api.definition.type.Label("Total Fee")
	private java.lang.Double totalFee;

	@org.kie.api.definition.type.Label("Payment Type")
	private java.lang.String paymentType;

	@org.kie.api.definition.type.Label("Loan rate History List")
	@javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private java.util.List<com.LoanRateHistory> loanRateHistoryList;

	@org.kie.api.definition.type.Label("Calculate Total Fee")
	private Double calculateTotalFee;

	@org.kie.api.definition.type.Label("Fee Calculation Formula")
	private java.lang.String feeCalculationFormula;

	@org.kie.api.definition.type.Label("Flat interest")
	private java.lang.Double flatInterest;

	@javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "Actual Interest Paid")
	private java.util.List<java.lang.Double> actualInterestPaid;

	public Prepayment() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.time.LocalDate getDate() {
		return this.date;
	}

	public void setDate(java.time.LocalDate date) {
		this.date = date;
	}

	public java.lang.Integer getNoOfMonths() {
		return this.noOfMonths;
	}

	public void setNoOfMonths(java.lang.Integer noOfMonths) {
		this.noOfMonths = noOfMonths;
	}

	public double getTotalInterest() {
		return this.totalInterest;
	}

	public void setTotalInterest(double totalInterest) {
		this.totalInterest = totalInterest;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.Integer getDaysToTerminate() {
		return this.daysToTerminate;
	}

	public void setDaysToTerminate(java.lang.Integer daysToTerminate) {
		this.daysToTerminate = daysToTerminate;
	}

	public java.lang.Double getTotalFee() {
		return this.totalFee;
	}

	public void setTotalFee(java.lang.Double totalFee) {
		this.totalFee = totalFee;
	}

	public java.lang.String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(java.lang.String paymentType) {
		this.paymentType = paymentType;
	}

	public java.util.List<com.LoanRateHistory> getLoanRateHistoryList() {
		return this.loanRateHistoryList;
	}

	public void setLoanRateHistoryList(
			java.util.List<com.LoanRateHistory> loanRateHistoryList) {
		this.loanRateHistoryList = loanRateHistoryList;
	}

	public java.lang.String getFeeCalculationFormula() {
		return this.feeCalculationFormula;
	}

	public void setFeeCalculationFormula(java.lang.String feeCalculationFormula) {
		this.feeCalculationFormula = feeCalculationFormula;
	}

	public java.lang.Double getCalculateTotalFee() {
		return this.calculateTotalFee;
	}

	public void setCalculateTotalFee(java.lang.Double calculateTotalFee) {
		this.calculateTotalFee = calculateTotalFee;
	}

	public java.lang.Double getFlatInterest() {
		return this.flatInterest;
	}

	public void setFlatInterest(java.lang.Double flatInterest) {
		this.flatInterest = flatInterest;
	}

	public java.util.List<java.lang.Double> getActualInterestPaid() {
		return this.actualInterestPaid;
	}

	public void setActualInterestPaid(
			java.util.List<java.lang.Double> actualInterestPaid) {
		this.actualInterestPaid = actualInterestPaid;
	}

	public Prepayment(java.lang.Long id, double totalInterest,
			java.lang.Double amount, java.time.LocalDate date,
			java.lang.Integer noOfMonths, java.lang.Integer daysToTerminate,
			java.lang.Double totalFee, java.lang.String paymentType,
			java.util.List<com.LoanRateHistory> loanRateHistoryList,
			java.lang.Double calculateTotalFee,
			java.lang.String feeCalculationFormula,
			java.lang.Double flatInterest,
			java.util.List<java.lang.Double> actualInterestPaid) {
		this.id = id;
		this.totalInterest = totalInterest;
		this.amount = amount;
		this.date = date;
		this.noOfMonths = noOfMonths;
		this.daysToTerminate = daysToTerminate;
		this.totalFee = totalFee;
		this.paymentType = paymentType;
		this.loanRateHistoryList = loanRateHistoryList;
		this.calculateTotalFee = calculateTotalFee;
		this.feeCalculationFormula = feeCalculationFormula;
		this.flatInterest = flatInterest;
		this.actualInterestPaid = actualInterestPaid;
	}

}