import com.Prepayment;
import com.LoanRateHistory;

rule "Prepayment Calculation"
    agenda-group "loan calculation"
    auto-focus true
when
		prepayment : Prepayment( paymentType == "Prepayment" )
	then
	    System.out.println("welcome to the prepayment calculation..!!");
		modify( prepayment ) {
				setTotalFee( (prepayment.getTotalInterest() / 100) * prepayment.getAmount() * prepayment.getDaysToTerminate() );
		}
end

rule "Terminate Account Calculation"
    agenda-group "loan calculation"
    auto-focus true
when
		prepayment : Prepayment( paymentType == "Termination" )
	then
	     System.out.println("welcome to the Termination calculation..!!");
	     double totalInterestPaid = 0.0;
	     for(Double actualInterestPaid : prepayment.getActualInterestPaid()){
	         totalInterestPaid += actualInterestPaid;
	     }
		modify( prepayment ) {
				setTotalFee( prepayment.getFlatInterest() - totalInterestPaid );
		}
end

rule "Terminate Actual lose of interest Calculation"
   agenda-group "loan calculation"
   auto-focus true
   
when
		prepayment : Prepayment( paymentType == "Termination Actual Loss Of Interest" )
		
	then
	    System.out.println("welcome to the Terminate Actual lose of interest Calculation..!!");
	    double totalFees = 0.0;
	    for(LoanRateHistory loanRateHistory : prepayment.getLoanRateHistoryList()){
	    System.out.println("totalFees1::"+totalFees+"::totalPaidAmount::"+loanRateHistory.getTotalAmountPaid()+"::rateOfInterest::"+loanRateHistory.getRateOfInterest()+"::totalDays::"+loanRateHistory.getTotalDays());
	        totalFees += (loanRateHistory.getTotalAmountPaid() * (loanRateHistory.getRateOfInterest() / 100) * (loanRateHistory.getTotalDays() / 360));
	        System.out.println("totalFees2::"+totalFees);
	    }
	    System.out.println("totalFees3::"+totalFees);
		modify( prepayment ) {
				setTotalFee( totalFees );
		}
end