import com.Prepayment;
import com.LoanRateHistory;

rule "Prepayment Calculation"
    agenda-group "loan calculation"
    auto-focus true
when
		prepayment : Prepayment( paymentType == "Prepayment" )
	then
	    System.out.println("welcome to the prepayment calculation..!!");
		modify( prepayment ) {
				setTotalFee( (prepayment.getTotalInterest() / 100) * prepayment.getAmount() * prepayment.getDaysToTerminate() );
		}
end

rule "Terminate Account Calculation"
    agenda-group "loan calculation"
    auto-focus true
when
		prepayment : Prepayment( paymentType == "Termination" )
	then
	     System.out.println("welcome to the Termination calculation..!!");
		modify( prepayment ) {
				setTotalFee( 200000 - prepayment.getActualInterestPaid() );
		}
end

rule "Terminate Actual lose of interest Calculation"
   agenda-group "loan calculation"
   auto-focus true
   
when
		prepayment : Prepayment( paymentType == "Termination Actual Loss Of Interest" )
		
	then
	    System.out.println("welcome to the Terminate Actual lose of interest Calculation..!!");
	    double totalFees = 0.0;
	    for(LoanRateHistory loanRateHistory : prepayment.getLoanRateHistoryList()){
	    System.out.println("CalculateTotalFee1::"+prepayment.getCalculateTotalFee()+"::totalPaidAmount::"+loanRateHistory.getTotalAmountPaid()+"::rateOfInterest::"+loanRateHistory.getRateOfInterest()+"::totalDays::"+loanRateHistory.getTotalDays());
	        prepayment.setCalculateTotalFee(loanRateHistory.getTotalAmountPaid() * (loanRateHistory.getRateOfInterest() / 100) * (loanRateHistory.getTotalDays() / 360));
	        System.out.println("CalculateTotalFee2::"+prepayment.getCalculateTotalFee());
	    }
	    System.out.println("CalculateTotalFee3::"+prepayment.getCalculateTotalFee());
		modify( prepayment ) {
				setTotalFee( prepayment.getCalculateTotalFee() );
		}
end