import com.Prepayment;
import com.LoanRateHistory;

rule "Prepayment Calculation"
    
when
		prepayment : Prepayment( paymentType == "Prepayment" )
	then
	    System.out.println("welcome to the prepayment calculation..!!");
		modify( prepayment ) {
				setTotalFee( prepayment.getTotalInterest() * prepayment.getAmount() * prepayment.getDaysToTerminate() );
		}
end

rule "Terminate Account Calculation"
    
when
		prepayment : Prepayment( paymentType == "Termination" )
	then
	    
		modify( prepayment ) {
				setTotalFee( 200000 - prepayment.getActualInterestPaid() );
		}
end

rule "Terminate Actual lose of interest Calculation"
   
when
		prepayment : Prepayment( paymentType == "Termination Actual Loss Of Interest" )
	then
	    double totalFees = 0;
	    for(LoanRateHistory loanRateHistory : prepayment.getLoanRateHistoryList()){
	        totalFees += (loanRateHistory.getTotalAmountPaid() * (loanRateHistory.getRateOfInterest() / 100) * (loanRateHistory.getTotalDays() / 360));
	    }
		modify( prepayment ) {
				setTotalFee( totalFees );
		}
end